import type { Task, AutopilotConfig, PublishResult } from '../types.js';

export type GitRunner = (
  args: string[],
  cwd: string,
) => Promise<{ stdout: string; exitCode: number }>;

export type GhRunner = (
  args: string[],
  cwd: string,
) => Promise<{ stdout: string; exitCode: number }>;

export interface PublisherDeps {
  git: GitRunner;
  gh: GhRunner;
}

function branchName(taskId: string, config: Pick<AutopilotConfig, 'git'>): string {
  return `${config.git.branchPrefix}${taskId}`;
}

export async function createBranch(
  taskId: string,
  config: Pick<AutopilotConfig, 'git'>,
  cwd: string,
  deps: PublisherDeps,
): Promise<string> {
  const branch = branchName(taskId, config);
  const base = config.git.baseBranch;

  await deps.git(['checkout', '-b', branch, base], cwd);
  return branch;
}

export async function commitChanges(
  taskId: string,
  cwd: string,
  deps: PublisherDeps,
): Promise<void> {
  await deps.git(['add', '-A'], cwd);
  await deps.git(['commit', '-m', `feat: implement ${taskId}`], cwd);
}

export async function pushBranch(
  branch: string,
  cwd: string,
  deps: PublisherDeps,
): Promise<void> {
  await deps.git(['push', '-u', 'origin', branch], cwd);
}

export async function createPR(
  task: Task,
  branch: string,
  config: Pick<AutopilotConfig, 'git'>,
  cwd: string,
  deps: PublisherDeps,
): Promise<{ prNumber: number; prUrl: string }> {
  const result = await deps.gh(
    [
      'pr', 'create',
      '--base', config.git.baseBranch,
      '--head', branch,
      '--title', `feat: ${task.id} — ${task.description}`,
      '--body', buildPRBody(task),
    ],
    cwd,
  );

  const prUrl = result.stdout.trim();
  const prNumber = parseInt(prUrl.split('/').pop() ?? '0', 10);

  return { prNumber, prUrl };
}

function buildPRBody(task: Task): string {
  const lines = [
    '## Summary',
    `- **Task ID**: ${task.id}`,
    `- **Mode**: ${task.mode}`,
    `- **Description**: ${task.description}`,
  ];

  if (task.detail) {
    lines.push(`- **Detail**: ${task.detail}`);
  }

  lines.push('', '*Generated by claude-autopilot*');
  return lines.join('\n');
}

export async function mergePR(
  prNumber: number,
  config: Pick<AutopilotConfig, 'merge'>,
  cwd: string,
  deps: PublisherDeps,
): Promise<void> {
  await deps.gh(
    ['pr', 'merge', String(prNumber), `--${config.merge.method}`, '--delete-branch'],
    cwd,
  );
}

export async function publish(
  task: Task,
  config: Pick<AutopilotConfig, 'git' | 'merge'>,
  cwd: string,
  deps: PublisherDeps,
): Promise<PublishResult> {
  const branch = await createBranch(task.id, config, cwd, deps);
  await commitChanges(task.id, cwd, deps);
  await pushBranch(branch, cwd, deps);

  const { prNumber, prUrl } = await createPR(task, branch, config, cwd, deps);

  let merged = false;
  if (task.mode === 'auto') {
    await mergePR(prNumber, config, cwd, deps);
    merged = true;
  }

  return { branch, prNumber, prUrl, merged };
}
